AddonId: VNDBMetadata
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-20
    PackageUrl: https://github.com/Mithnar/PlayniteVndb/releases/download/2.0/PlayniteVndb_2_0.pext
    Changelog:
      - Playnite 9 support
